version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout

notify:
  webhooks:
    - url: https://galaxy.ansible.com/api/v1/notifications/
